github:
  is_project_page: false
title: Ben Grudzien
description: A collection of engineering projects spanning robotics, simulation, and electronics
show_downloads: false
theme: jekyll-theme-hacker
markdown: GFM

